name: release
on:
  push:
    tags:
      - "*"

jobs:
  call_release_reusable:
    uses: awsdevops-sbs/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-backend
      npm_install: true

    secrets: inherit